---
title: "Ti for reference"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
tf=c(2,6.5,2.5,6,5,3.5,3,3.5)
weibull_scale=c(2365.08,996.88,713.55,1406.84,343.76,3933.12,828.19,2040.95)
weibull_shape=c(414.16,109.25,79.81,115.21,169.81,143.60,43.83,296.48)
optimal_replace=c(1440,1830,2000,2160,248,2250,306,1400)
tp=c(0.4,5.42,0.625,0.857,1.25,0.7,0.429,0.875)

######
#require(pracma)
library(pracma)

shape <- 1
scale <- 4
aa <- 0
bb <- 3



set.seed(1)
foo <- rweibull(1e5,shape,scale)
max(foo)
min(foo)

mean(foo[foo>aa & foo<bb])

scale*(gammainc((bb/scale)^shape,1/shape+1)["lowinc"]-gammainc((aa/scale)^shape,1/shape+1)["lowinc"])/
  (exp(-(aa/scale)^shape)-exp(-(bb/scale)^shape))


```
```{r}
############tire 

i = 1

shape <- weibull_shape[i]
scale <- weibull_scale[i]

foo <- rweibull(100000,weibull_shape[i],weibull_scale[i])

mean(foo)
max(foo)
min(foo)

 

D1 <- function (t) {
  
  (tp[i]*(1- pweibull(t,shape=weibull_shape[i],scale=weibull_scale[i])) + tf[i]*pweibull(t,shape=weibull_shape[i],scale=weibull_scale[i]))/
    ((t+tp[i]) *(1 - pweibull(t,shape=weibull_shape[i],scale=weibull_scale[i])) + (tf[i]+(mean(foo[foo>0 & foo<t]))) * pweibull(t,shape=weibull_shape[i],scale=weibull_scale[i]))
  
}

t = seq(0,2500,1)

plot(t,sapply(t, function(x) D1(x)))

t = seq(2300,2350,1)

plot(t,sapply(t, function(x) D1(x)))

out <- nlminb(c(2320), D1, lower=c(0), upper = c(Inf))
out


```
```{r}
############transmission 

i = 2

shape <- weibull_shape[i]
scale <- weibull_scale[i]

foo <- rweibull(100000,weibull_shape[i],weibull_scale[i])

mean(foo)
max(foo)
min(foo)

 

D1 <- function (t) {
  
  (tp[i]*(1- pweibull(t,shape=weibull_shape[i],scale=weibull_scale[i])) + tf[i]*pweibull(t,shape=weibull_shape[i],scale=weibull_scale[i]))/
    ((t+tp[i]) *(1 - pweibull(t,shape=weibull_shape[i],scale=weibull_scale[i])) + (tf[i]+(mean(foo[foo>0 & foo<t]))) * pweibull(t,shape=weibull_shape[i],scale=weibull_scale[i]))
  
}

t = seq(0,2500,1)

plot(t,sapply(t, function(x) D1(x)))

t = seq(960,980,1)

plot(t,sapply(t, function(x) D1(x)))

out <- nlminb(c(1000), D1, lower=c(0), upper = c(Inf))
out

```

